### ISSUE TITLE
Service architecture

### ISSUE THREAD

**Issue by sagikazarmark** [indigophp/guardian#5]
The different part of authentication/session management processes does not always require all dependencies. For example the session check does not require the authentication part.

Possible services:
- Login/Authentication
- SessionResume/Check
- Logout

**Comment by sagikazarmark** [comment]
In practice it seems that services are usually NOT used on their own (for example logout is never used on its own), thus the unnecessary dependency argument is not valid anymore. The three classes could be merged into one.

It also turned out that these services are heavily tied to the usual user-password authentication used in web applications which makes me think that these classes should go elsewhere.

@TamasBarta thoughts?

**Comment by sagikazarmark** [comment]
Actually everything related to user-password authentication could be moved into a separate package:
UserPassword authenticator
User caller
etc

It would make more sense to keep those in one package rather than moving only the current services.

Or they could all remain in the core package, but that would mean that guardian has more focus on that type of authentication (which is not true, it tries to be general).

**Comment by TamasBarta** [comment]
I originally suggested the three service to be merged, since they all share a login flow responsibility. They are also very small in size, so separating them means unnecessary complication, IMHO.

What I also suggested is the merged class to be included in the base package. I believe it's not necessary to create tons of packages. We need an aim with this framework, and that could be "a very flexible framework that can be easily used for any purpose of authentication", but that does not imply it shouldn't work out of the box for the most common scenarios (eg: web application authentication). Also It doesn't have any bad impact to simply include classes for the most common case.

**Comment by sagikazarmark** [comment]
Makes sense.

What I am concerned about is to make the package as general as possible. I am afraid that if we include too much "common use case" stuff, the development will go in an unwanted direction.

But for now, I will just merge the three.

Any idea for a name? (Something different from Guardian)

**Comment by sagikazarmark** [comment]
@TamasBarta renamed to SessionAuth and RequestAuth. It is subject of change if we can pick a better name.

**Comment by TamasBarta** [comment]
I'm fine with that too.

2015-04-20 20:43 keltezéssel, Márk Sági-Kazár írta:
